### ISSUE TITLE
the code throws unwanted errors

### ISSUE THREAD

**Issue by himalayafan** [localvoid/kivi#2]
Hi! Impressed by your work even if your readme was trying to scare me off :)

I was playing around a little and noticed that string children within an array will throw if you are not creating a text object. Is that a expected behaviour? If so, maybe an idea to notify about it. Or add support?

```
// Throws an error
['abc', 'def', 'ghi']
```

**Comment by localvoid** [comment]
Hi, children property supports only `Array<VNode>|string` types, closure compiler should catch such errors https://github.com/localvoid/kivi/blob/b55b14a689f312d5fe5a59630b281b4ba37ef762/src/vnode/vnode.js#L318

The main reason why it doesn't support `Array<string|VNode>|string` is because it is possible to override `insertChild`,`moveChild`, etc to implement complicated animations, and params of this functions should be VNodes in case we want to delay appearence and create comment tag as a placeholder instead of real element.
